---
title: "DowJones index Forecasing Model 2024-2026"
author: "JDRK"
date: "2024-09-06"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float: 
     collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
library(hrbrthemes)
library(prettydoc)

library(pacman)

p_load("quantmod","stringr","forecast","tseries","janitor",
       "formattable","data.table","gt","DT","scales","tibble",
       "ggplot2","plotly","GGally","openxlsx","readxl","dplyr","tidyr","lubridate")

library(lubridate)

dw<-getSymbols("^DJI",from="1900-01-01")

dw <-rownames_to_column(data.frame( DJI)) %>% select(c(1,7)) %>% 
rename(date=rowname,price=DJI.Adjusted) %>% 
mutate(date=ymd(date)) %>% 
mutate(wk=round_date(date,"week"),mn=round_date(date,"month")) %>% arrange(date)


# months Last

dwm<-dw %>%  group_by(mn) %>% summarize(prices=mean(price))

dwts<-ts(dwm$prices,start = c(1992,1),end = c(2023,9),frequency = 12)


dwets<-ets(dwts)

dwfor<-forecast(dwets,h = 12)


months_last_chart<-
cbind(
    dwm[c(382:393),] ,
    rownames_to_column(as.data.frame(dwfor))
) %>% select(c(1,2,6)) %>% rename(date=mn) %>% clean_names() %>% mutate(date=as.POSIXct(date)) %>% pivot_longer(!date,names_to = "levels",values_to = "prices") %>% ggplot(aes(x=date,y=prices,group=levels,color=levels))+geom_line(size=1.3)+geom_point(size=3)+scale_color_brewer(palette = "Set1")+geom_label(aes(label=round(prices/1000,2)),size=3,nudge_x =.25 ,nudge_y = .25,size = 1)+labs(x="",y="",title = "Detect Last Year DowJones Prices Model",subtitle = "Data Focus Period: 1992 - Sep 2023")+scale_y_continuous(labels = comma)+theme_bw()+theme(axis.text.x = element_text(face = "bold",color="black"),axis.text.y = element_text(face = "bold",color="black"),legend.position = "top",plot.title = element_text(color = "#2c3e50",face = "bold"))+scale_x_datetime(date_breaks ="month" ,date_labels = "%b-%y")  
  


months_last_gt<-
cbind(
dwm[c(382:393),] ,
rownames_to_column(as.data.frame(dwfor))
) %>% select(c(1,2,6)) %>% rename(date=mn) %>% clean_names() %>% 
gt() %>%
tab_row_group(rows = date<="2023-12-31" ,label = "2023",id="2023") %>% 
tab_row_group(rows = date>="2024-1-1" & date<="2024-12-01",label = "2024",id="2024") %>% 
row_group_order(groups = c("2023","2024")) %>% 
tab_header(title = "Detect Forecast DowJones Index Model",subtitle = "Period: 12 Months Last.") %>% 
tab_stubhead(label = "Years") %>% 
cols_label_with(columns = everything(),fn = toupper) %>% 
tab_style(style =cell_text(align = "center",weight = "bold") ,locations = cells_body()) %>% 
fmt_number(columns = c(2:3),decimals = 2) %>%
fmt_date(columns = 1,date_style = "yMMM") %>% 
tab_style(style =list(cell_text(weight = "bold"),cell_fill("gray")) ,locations = cells_row_groups()) %>% 
opt_stylize(style = 3) %>% tab_style(style =list(cell_text(weight = "bold")) ,locations = cells_column_labels()) %>% 
tab_style(style = list(cell_text(weight = "bold",color="white"),cell_fill("#A04747")),locations = cells_title()) %>% 
summary_rows(groups =everything(),fns =list(Mean=~mean(.)),columns = c(2,3)) %>% 
tab_style(style = list(cell_text(weight = "bold"),cell_fill("#FCDE70")),
locations = cells_summary()) %>% 
tab_style(style = list(cell_text(weight = "bold"),cell_fill("#FCDE70")),locations = cells_stub_summary())  










#Real

dwrts<-ts(dwm$prices,start = c(1992,1),end = c(2024,9),frequency = 12)



dwrets<-ets(dwrts)

dwrfor<-forecast(dwrets,h = 12)


months_next_chart<-
cbind(
data.frame(date=seq(as.Date("2024-10-01"),by="month",len=12))
,
rownames_to_column(as.data.frame(dwrfor)) %>% select(c(4))) %>% 
mutate(date=as.POSIXct(date)) %>% clean_names() %>% 
ggplot(aes(x=date,y=hi_80))+geom_line(size=1.3)+geom_point(size=3)+
geom_label(aes(label=paste0(round(hi_80/1000,2),"K"),nudge_x =.25 ,nudge_y = .25))+
labs(x="",y="",title = "Detect Next Year DowJones Prices Model",subtitle = "Data Focus Period: 1992 - Sep 2024")+scale_y_continuous(labels = comma)+theme_bw()+theme(axis.text.x = element_text(face = "bold",color="black"),axis.text.y = element_text(face = "bold",color="black"),legend.position = "top",plot.title = element_text(color = "#2c3e50",face = "bold"))+scale_x_datetime(date_breaks ="month" ,date_labels = "%b-%y")
  




months_next_gt<-
cbind(
data.frame(date=seq(as.Date("2024-10-01"),by="month",len=12)),
rownames_to_column(as.data.frame(dwrfor)) %>% select(c(3,4))) %>% 
clean_names() %>% mutate(prices="") %>% select(1,2,3) %>% gt() %>%
tab_row_group(rows = date>="2024-10-1" & date<="2024-12-01",label = "2024",id="2024") %>% 
tab_row_group(rows = date>="2025-1-1" & date<="2025-12-01",label = "2025",id="2025") %>% 
row_group_order(groups = c("2024","2025")) %>% 
tab_header(title = "Forecast DowJones Index",subtitle = "Period: 18 Months Next.") %>% 
tab_stubhead(label = "Years") %>% 
cols_label_with(columns = everything(),fn = toupper) %>% 
tab_style(style =cell_text(align = "center",weight = "bold") ,locations = cells_body()) %>% 
fmt_number(columns = c(2:3),decimals = 2) %>%
fmt_date(columns = 1,date_style = "yMMM") %>% 
tab_style(style =list(cell_text(weight = "bold"),cell_fill("gray")) ,locations = cells_row_groups()) %>% 
opt_stylize(style = 3) %>% tab_style(style =list(cell_text(weight = "bold")) ,locations = cells_column_labels()) %>% 
tab_style(style = list(cell_text(weight = "bold",color="white"),cell_fill("#A04747")),locations = cells_title()) %>% 
summary_rows(groups = everything(),fns =list(Mean=~mean(.)),columns = c(2,3)) %>% 
tab_style(style = list(cell_text(weight = "bold"),cell_fill("#FCDE70")),
locations = cells_summary()) %>% 
tab_style(style = list(cell_text(weight = "bold"),cell_fill("#FCDE70")),locations = cells_stub_summary())  

```


### Last Year Forecast Charts

```{r echo=FALSE,message=FALSE,warning=FALSE}
autoplot(decompose(diff(dwts)))
         
```


```{r echo=FALSE,message=FALSE,warning=FALSE}
months_last_chart
```



### Last Year Forecast
```{r echo=FALSE,message=FALSE,warning=FALSE}
months_last_gt
```


### Forecast Next Charts

```{r echo=FALSE,message=FALSE,warning=FALSE}

autoplot(decompose(diff(dwrts)))

```



```{r echo=FALSE,message=FALSE,warning=FALSE}
months_next_chart
```

### Forecast Table  
```{r echo=FALSE,message=FALSE,warning=FALSE}
months_next_gt
```

